export interface Pais {
    id:number,
    nombre:string
}

export const ListaPAises:Array<Pais>=[
    {
        id:1,
        nombre:"Afganistan"
    },{
        id:2,
        nombre:"Albania"
    },{
        id:3,
        nombre:"Alemania"
    },{
        id:4,
        nombre:"Andorra"
    },{
        id:5,
        nombre:"Angola"
    },{
        id:6,
        nombre:"Antigua y Barbuda"
    },{
        id:7,
        nombre:"Arabia Saudita / Arabia Saudí"
    },{
        id:8,
        nombre:"Argelia"
    },{
        id:9,
        nombre:"Argentina"
    },{
        id:10,
        nombre:"Armenia"
    },{
        id:11,
        nombre:"Australia"
    },{
        id:12,
        nombre:"Austria"
    },{
        id:13,
        nombre:"Azerbaiyán"
    },{
        id:14,
        nombre:"Bahamas"
    },{
        id:15,
        nombre:"Bangladés"
    },{
        id:16,
        nombre:"Barbados"
    },{
        id:17,
        nombre:"Baréin"
    },{
        id:18,
        nombre:"Bélgica"
    },{
        id:19,
        nombre:"Belice"
    },{
        id:20,
        nombre:"Bielorrusia"
    },{
        id:21,
        nombre:"Benín"
    },{
        id:22,
        nombre:"Birmania / Myanmar"
    },{
        id:23,
        nombre:"Bolivia"
    },{
        id:24,
        nombre:"Bosnia y Herzegovina / Bosnia-Herzegovina"
    },{
        id:25,
        nombre:"Botsuana"
    },{
        id:26,
        nombre:"Brasil"
    },{
        id:27,
        nombre:"Brunei"
    },{
        id:28,
        nombre:"Bulgaria"
    },{
        id:29,
        nombre:"Burkina Faso"
    },{
        id:30,
        nombre:"Burundi"
    },{
        id:31,
        nombre:"Bután"
    },{
        id:32,
        nombre:"Cabo Verde"
    },{
        id:33,
        nombre:"Camboya"
    },{
        id:34,
        nombre:"Camerún"
    },{
        id:35,
        nombre:"Canadá"
    },{
        id:36,
        nombre:"Catar"
    },{
        id:37,
        nombre:"República Centroafricana"
    },{
        id:38,
        nombre:"Chad"
    },{
        id:39,
        nombre:"República Checa / Chequia"
    },{
        id:40,
        nombre:"Chile"
    },{
        id:41,
        nombre:"China"
    },{
        id:42,
        nombre:"Chipre"
    },{
        id:43,
        nombre:"Colombia"
    },{
        id:44,
        nombre:"Comoras"
    },{
        id:45,
        nombre:"República del Congo"
    },{
        id:46,
        nombre:"República Democrática del Congo"
    },{
        id:47,
        nombre:"Corea del Norte"
    },{
        id:48,
        nombre:"Corea del Sur"
    },{
        id:49,
        nombre:"Costa de Marfil"
    },{
        id:49,
        nombre:"Costa Rica"
    },{
        id:50,
        nombre:"Croacia"
    },{
        id:51,
        nombre:"Cuba"
    },{
        id:52,
        nombre:"Dinamarca"
    },{
        id:53,
        nombre:"Dominica"
    },{
        id:54,
        nombre:"República Dominicana"
    },{
        id:55,
        nombre:"Ecuador"
    },{
        id:56,
        nombre:"Egipto"
    },{
        id:57,
        nombre:"El Salvador"
    },{
        id:58,
        nombre:"Emiratos Árabes Unidos"
    },{
        id:59,
        nombre:"Eritrea"
    },{
        id:60,
        nombre:"Eslovaquia"
    },{
        id:61,
        nombre:"Eslovenia"
    },{
        id:62,
        nombre:"España"
    },{
        id:63,
        nombre:"Estados Unidos"
    },{
        id:64,
        nombre:"Estonia"
    },{
        id:65,
        nombre:"Etiopía"
    },{
        id:66,
        nombre:"Filipinas"
    },{
        id:67,
        nombre:"Finlandia"
    },{
        id:68,
        nombre:"Fiyi"
    },{
        id:69,
        nombre:"Francia"
    },{
        id:70,
        nombre:"Gabón"
    },{
        id:71,
        nombre:"Gambia"
    },{
        id:72,
        nombre:"Georgia"
    },{
        id:73,
        nombre:"Ghana"
    },{
        id:74,
        nombre:"Granada"
    },{
        id:75,
        nombre:"Grecia"
    },{
        id:76,
        nombre:"Guatemala"
    },{
        id:77,
        nombre:"Guinea"
    },{
        id:78,
        nombre:"Guinea-Bisáu"
    },{
        id:79,
        nombre:"Guinea Ecuatorial"
    },{
        id:80,
        nombre:"Guyana"
    },{
        id:81,
        nombre:"Haití"
    },{
        id:82,
        nombre:"Honduras"
    },{
        id:83,
        nombre:"Hungría"
    },{
        id:84,
        nombre:"India"
    },{
        id:85,
        nombre:"Indonesia"
    },{
        id:86,
        nombre:"Irak"
    },{
        id:87,
        nombre:"Irán"
    },{
        id:88,
        nombre:"Irlanda"
    },{
        id:89,
        nombre:"Islandia"
    },{
        id:90,
        nombre:"Israel"
    },{
        id:91,
        nombre:"Italia"
    },{
        id:92,
        nombre:"Jamaica"
    },{
        id:93,
        nombre:"Japón"
    },{
        id:94,
        nombre:"Jordania"
    },{
        id:95,
        nombre:"Kazajistán"
    },{
        id:96,
        nombre:"Kenia"
    },{
        id:97,
        nombre:"Kirguistán"
    },{
        id:98,
        nombre:" Kiribati"
    },{
        id:99,
        nombre:"Kuwait"
    },{
        id:100,
        nombre:"Laos"
    },{
        id:101,
        nombre:"Lesoto"
    },{
        id:102,
        nombre:"Letonia"
    },{
        id:103,
        nombre:"Líbano"
    },{
        id:104,
        nombre:"Liberia"
    },{
        id:105,
        nombre:"Libia"
    },{
        id:106,
        nombre:"Liechtenstein"
    },{
        id:107,
        nombre:"Lituania"
    },{
        id:108,
        nombre:"Luxemburgo"
    },{
        id:109,
        nombre:"Macedonia del Norte"
    },{
        id:110,
        nombre:"Madagascar"
    },{
        id:111,
        nombre:"Malasia"
    },{
        id:112,
        nombre:"Malaui"
    },{
        id:113,
        nombre:"Maldivas"
    },{
        id:114,
        nombre:"Mali / Malí"
    },{
        id:115,
        nombre:"Malta"
    },{
        id:116,
        nombre:"Marruecos"
    },{
        id:117,
        nombre:"Islas Marshall"
    },{
        id:118,
        nombre:"Mauricio"
    },{
        id:119,
        nombre:"Mauritania"
    },{
        id:120,
        nombre:"México"
    },{
        id:121,
        nombre:"Micronesia"
    },{
        id:120,
        nombre:"Moldavia"
    },{
        id:121,
        nombre:"Mónaco"
    },{
        id:122,
        nombre:"Mongolia"
    },{
        id:123,
        nombre:"Montenegro"
    },{
        id:124,
        nombre:"Mozambique"
    },{
        id:125,
        nombre:"Namibia"
    },{
        id:126,
        nombre:"Nauru"
    },{
        id:127,
        nombre:"Nepal"
    },{
        id:128,
        nombre:"Nicaragua"
    },{
        id:129,
        nombre:"Níger"
    },{
        id:130,
        nombre:"Nigeria"
    },{
        id:131,
        nombre:"Noruega"
    },{
        id:132,
        nombre:"Nueva Zelanda / Nueva Zelandia"
    },{
        id:133,
        nombre:"Omán"
    },{
        id:134,
        nombre:"Países Bajos"
    },{
        id:135,
        nombre:"Pakistán"
    },{
        id:136,
        nombre:"Palaos"
    },{
        id:137,
        nombre:"Palestina"
    },{
        id:138,
        nombre:"Panamá"
    },{
        id:139,
        nombre:"Papúa Nueva Guinea"
    },{
        id:140,
        nombre:"Paraguay"
    },{
        id:141,
        nombre:"Perú"
    },{
        id:142,
        nombre:"Polonia"
    },{
        id:143,
        nombre:"Portugal"
    },{
        id:144,
        nombre:"Reino Unido"
    },{
        id:145,
        nombre:"Ruanda"
    },{
        id:146,
        nombre:"Rumania / Rumanía"
    },{
        id:147,
        nombre:"Rusia"
    },{
        id:148,
        nombre:"Islas Salomón"
    },{
        id:149,
        nombre:"Samoa"
    },{
        id:150,
        nombre:"San Cristóbal y Nieves"
    },{
        id:151,
        nombre:"San Marino"
    },{
        id:152,
        nombre:"San Vicente y las Granadinas"
    },{
        id:153,
        nombre:"Santa Lucía"
    },{
        id:154,
        nombre:"Santo Tomé y Príncipe"
    },{
        id:155,
        nombre:"Senegal"
    },{
        id:156,
        nombre:"Serbia"
    },{
        id:157,
        nombre:"Seychelles"
    },{
        id:158,
        nombre:"Sierra Leona"
    },{
        id:159,
        nombre:"Singapur"
    },{
        id:160,
        nombre:"Siria"
    },{
        id:161,
        nombre:"Somalia"
    },{
        id:162,
        nombre:"Sri Lanka"
    },{
        id:163,
        nombre:"Suazilandia / Esuatini"
    },{
        id:164,
        nombre:"Sudáfrica"
    },{
        id:165,
        nombre:"Sudán"
    },{
        id:166,
        nombre:"Sudán del Sur"
    },{
        id:167,
        nombre:"Suecia"
    },{
        id:168,
        nombre:"Suiza"
    },{
        id:169,
        nombre:"Surinam"
    },{
        id:170,
        nombre:"Tailandia"
    },{
        id:171,
        nombre:"Tanzania"
    },{
        id:172,
        nombre:"Tayikistán"
    },{
        id:173,
        nombre:"Timor Oriental"
    },{
        id:174,
        nombre:"Togo"
    },{
        id:175,
        nombre:"Tonga"
    },{
        id:176,
        nombre:"Trinidad y Tobago"
    },{
        id:177,
        nombre:"Túnez"
    },{
        id:178,
        nombre:"Turkmenistán"
    },{
        id:179,
        nombre:"Turquía"
    },{
        id:180,
        nombre:"Tuvalu"
    },{
        id:181,
        nombre:"Ucrania"
    },{
        id:182,
        nombre:"Uganda"
    },{
        id:183,
        nombre:"Uruguay"
    },{
        id:184,
        nombre:"Uzbekistán"
    },{
        id:185,
        nombre:"Vanuatu"
    },{
        id:186,
        nombre:"Ciudad del Vaticano"
    },{
        id:187,
        nombre:"Venezuela"
    },{
        id:188,
        nombre:"Vietnam"
    },{
        id:189,
        nombre:"Yemen"
    },{
        id:190,
        nombre:"Yibuti"
    },{
        id:191,
        nombre:"Zambia"
    },{
        id:192,
        nombre:"Zimbabue"
    }
]